#配置数据源
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iadmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    druid:
      # 最大连接数
      max-active: 20
      # 初始连接数
      initial-size: 1
      # 获取连接超时时间
      max-wait: 60000
      # 最小连接池数量
      min-idle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置检测连接是否有效
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.46.120
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.46.121
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

  data:
    redis:
      #数据库索引
      database: 8
      host: localhost
      port: 6379
      #    password:
      #连接超时时间
      timeout: 5000m

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时
  token-validity-in-seconds: 14400000

# 文件存储路径
file:
  path: D:\web\iadmin\file\
  avatar: D:\web\iadmin\avatar\
  # 文件大小/M
  maxSize: 50
  avatarMaxSize: 5

# RSA 密钥配置
rsa:
  private_key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEA1Vb98wHg0dyEA5HBYqJzfvmWslP0O172eUJoe3+IJ0gDUNgisDRdfV9SBgtN2D5CDNQP9Iw5e8fzcktY3+RbsQIDAQABAkEAjb2MX6XBzuypsQ1n5LZ18ci1vKlWvRNswkfCzzp+JUnWiiQDKmfa9QrkRievNioFt0y71uQAMgOQ64G+SRGFGQIhAOyqvYcyBtHNnDeuYYdGbJhkOr0tRZdpoWuc9CPj0X5nAiEA5sRtMXkyrRyIE/OGm+LdaRJaxZTX8QTmWIWEregw1icCIA2cUCQLS3sbYQWOwMsf0LT+5qXkiaEIkSD4OM4rluu3AiEAyVZZmo+OqkC5bQbMy9c8q/6qmbZKTWuj+VnMr9pkOYMCIGPBCrhhZv/RMuuj+y3BA/UD7oUfjUs3bo84MfgZuMJD
  public_key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANVW/fMB4NHchAORwWKic375lrJT9Dte9nlCaHt/iCdIA1DYIrA0XX1fUgYLTdg+QgzUD/SMOXvH83JLWN/kW7ECAwEAAQ==